import all_classes
ecar_obj = all_classes.Electric_car(brand = "Tesla" , model = "Model8" , year = 2024 , battery_size = "80Kwh")
car_obj = all_classes.Car(brand = "Tata" , model = "Nano" , year = 2022 , milege = "80KM")
print(ecar_obj.get_model())
print(ecar_obj.get_brand())
print(ecar_obj.get_year())
print(ecar_obj.get_battery_size())
ecar_obj.print_full_name()
print(ecar_obj.fuel_type())
print("--------------------------")
print(car_obj.get_brand() , car_obj.get_model() , car_obj.get_year() , car_obj.get_milege()) 
car_obj.print_full_name()
print(car_obj.fuel_type())
print(ecar_obj.Total_counter)
print(car_obj.Total_counter)
print(ecar_obj.Ecar_counter)
# print(car_obj.Ecar_counter)
ecar2 = all_classes.Electric_car(brand = "Tesla" , model = "old_model" , battery_size = 55)
print("------------------")
print(ecar2.Total_counter)
print(car_obj.Total_counter)
print(ecar_obj.Total_counter)
print(ecar_obj.Ecar_counter)
print(ecar2.Ecar_counter)
print("-----------")
print(all_classes.Car.Total_counter)
print(all_classes.Car.Ecar_counter)
print(all_classes.Electric_car.Ecar_counter)
print(all_classes.Electric_car.Total_counter)
print(all_classes.Car.__dict__)
print("::::::::::::::::::")
print(all_classes.Electric_car.__dict__)
print("::::::::::::::::::::")
print(ecar_obj.__dict__)
print("::::::::::::::::::")
print(car_obj.__dict__)
print(":::::::::::::::")
print(ecar2.__dict__)


