import all_classes
electric_car_obj:object = all_classes.Electric_car(brand = "Tesla" , model = "new_model" , battery_size = 24)
print(electric_car_obj._Electric_car__brand)
# print(electric_car_obj._Car__model)
print(electric_car_obj._Electric_car__battery_size)
electric_car_obj.print_full_name()
print('electric_car_obj.brand , "or" , electric_car_obj.__brand "will not work anymore"')
print(electric_car_obj.get_brand())
print(electric_car_obj.get_battery_size())
print(electric_car_obj.get_model())
print(electric_car_obj.Total_counter)
